// Code generated by AI triage behavior loop. DO NOT EDIT.
// jobId: f7168625-1823-4dc2-8eb2-d6d7e248b2b4

package buyerflow_test

import (
	"testing"

	"encore.app/wabantu/internal/buyerflow"
	"encore.app/wabantu/internal/triageassert"
)

func TestBehavior_f7168625_1823_4dc2_8eb2_d6d7e248b2b4(t *testing.T) {
	sim := buyerflow.NewOmahSimulator()
	out := sim.Turn("hah ? nambah abon sapi 125 gram 1, abon sapi 500 gram 1")
	spec := triageassert.CommerceSpec{
		WantPath: "order_flow",
		Include: []triageassert.CartItem{{NameContains: "abon sapi 125 gram", Qty: 1}, {NameContains: "abon sapi 500 gram", Qty: 1}},
		WantNot: []string{"belum menemukan"},
	}
	if err := triageassert.CheckTurn(out, spec); err != nil {
		t.Fatal(err)
	}
}
