// Code generated by AI triage loop. DO NOT EDIT.
// jobId: 6c43985f-58e1-4b8f-ad51-4276b69d4c49

package buyerflow

import "testing"

func mustTriageAutoGenSimulator(t *testing.T) *Simulator {
	t.Helper()
	sim, err := simulatorFromTriageAutoGenSnapshot()
	if err != nil {
		t.Fatalf("triage snapshot: %v", err)
	}
	return sim
}

func TestRegressionAutoGen(t *testing.T) {
	cases := conversationRegressionAutoGenCases()
	if len(cases) == 0 {
		t.Skip("no auto-generated regression cases")
	}
	sim := mustTriageAutoGenSimulator(t)
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			local := mustTriageAutoGenSimulator(t)
			local.History = append([]Message{}, sim.History...)
			local.Order = sim.Order
			for _, prior := range tc.priorInputs {
				local.Turn(prior)
			}
			out := local.Turn(tc.input)
			if tc.extraCheck != nil {
				tc.extraCheck(t, out)
				return
			}
			if tc.wantPath != "" && out.Path != tc.wantPath {
				t.Fatalf("path = %q want %q reply=%q", out.Path, tc.wantPath, out.Reply)
			}
		})
	}
}
