// Code generated by AI triage loop. DO NOT EDIT.
// jobId: (none — re-run loop to populate)

package ai

import "testing"

// Code generated by AI triage loop. Review before merge.
// tenantSchema: (pending)

const triageAutoGenSnapshotJSON = ""

func conversationRegressionAutoGenCases() []conversationRegressionCase {
	return nil
}

func mustTriageAutoGenSimulator(t *testing.T) *ConversationSimulator {
	t.Helper()
	if triageAutoGenSnapshotJSON == "" {
		return newOmahSimulator()
	}
	sim, err := SimulatorFromSnapshotJSON(triageAutoGenSnapshotJSON)
	if err != nil {
		t.Fatalf("triage snapshot: %v", err)
	}
	return sim
}

func TestConversationRegressionAutoGen(t *testing.T) {
	cases := conversationRegressionAutoGenCases()
	if len(cases) == 0 {
		t.Skip("no auto-generated regression cases")
	}
	sim := mustTriageAutoGenSimulator(t)
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			local := mustTriageAutoGenSimulator(t)
			local.History = append([]dbMessage{}, sim.History...)
			local.Order = sim.Order
			for _, prior := range tc.priorInputs {
				local.Turn(prior)
			}
			out := local.Turn(tc.input)
			if tc.extraCheck != nil {
				tc.extraCheck(t, out)
				return
			}
			if tc.wantPath != "" && out.Path != tc.wantPath {
				t.Fatalf("path = %q want %q reply=%q", out.Path, tc.wantPath, out.Reply)
			}
		})
	}
}
