// Code generated by AI triage loop. DO NOT EDIT.
// jobId: 97702213-080b-4f7e-a420-86f332639354

package ai

import "testing"

// Code generated by AI triage loop. Review before merge.
// tenantSchema: t_omah_apparel

func conversationRegressionAutoGenCases() []conversationRegressionCase {
	return []conversationRegressionCase{
		{
			name: "triage_1df31813_0",
			input: "FORVERFRISK XL ada ?",
			wantPath: PathConsulting,
		},
	}
}

func TestConversationRegressionAutoGen(t *testing.T) {
	cases := conversationRegressionAutoGenCases()
	if len(cases) == 0 {
		t.Skip("no auto-generated regression cases")
	}
	sim := newOmahSimulator()
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			local := newOmahSimulator()
			local.History = append([]dbMessage{}, sim.History...)
			local.Order = sim.Order
			out := local.Turn(tc.input)
			if tc.extraCheck != nil {
				tc.extraCheck(t, out)
				return
			}
			if tc.wantPath != "" && out.Path != tc.wantPath {
				t.Fatalf("path = %q want %q reply=%q", out.Path, tc.wantPath, out.Reply)
			}
		})
	}
}
