// Command triage-apply writes ai/conversation_regression_auto_gen_test.go from stdin.
//
// Usage:
//
//	go run scripts/triage-apply.go --job-id <uuid> < regression_snippet.go
//
// Stdin must contain the output of ai.GenerateRegressionCases (package ai + cases function).
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	jobID := flag.String("job-id", "", "ai_triage_job id")
	outPath := flag.String("out", "internal/buyerflow/regression_autogen_test.go", "output path relative to api-go root")
	flag.Parse()

	if strings.TrimSpace(*jobID) == "" {
		fatal("job-id required")
	}

	root, err := repoRoot()
	if err != nil {
		fatal(err.Error())
	}

	body, err := io.ReadAll(os.Stdin)
	if err != nil {
		fatal(err.Error())
	}
	content := strings.TrimSpace(string(body))
	if content == "" {
		fatal("stdin empty: regression cases required")
	}
	if !strings.Contains(content, "triageAutoGenSnapshotJSON") {
		content = "const triageAutoGenSnapshotJSON = \"\"\n\n" + content
	}

	target := filepath.Join(root, *outPath)
	file := buildAutoGenTestFile(*jobID, content)
	if err := os.WriteFile(target, []byte(file), 0o644); err != nil {
		fatal(err.Error())
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", target)
}

func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "encore.app")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("encore.app not found from cwd")
		}
		dir = parent
	}
}

func buildAutoGenTestFile(jobID, generated string) string {
	generated = strings.TrimSpace(generated)
	// Strip duplicate package line if present; triage-apply owns file header.
	if strings.HasPrefix(generated, "package ai") {
		generated = strings.TrimSpace(strings.TrimPrefix(generated, "package ai"))
	}

	var b strings.Builder
	b.WriteString("// Code generated by AI triage loop. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// jobId: %s\n\n", jobID))
	b.WriteString("package ai\n\n")
	b.WriteString("import \"testing\"\n\n")
	b.WriteString(generated)
	if !strings.HasSuffix(generated, "\n") {
		b.WriteString("\n")
	}
	b.WriteString(`
func mustTriageAutoGenSimulator(t *testing.T) *ConversationSimulator {
	t.Helper()
	if triageAutoGenSnapshotJSON == "" {
		return newOmahSimulator()
	}
	sim, err := SimulatorFromSnapshotJSON(triageAutoGenSnapshotJSON)
	if err != nil {
		t.Fatalf("triage snapshot: %v", err)
	}
	return sim
}

func TestConversationRegressionAutoGen(t *testing.T) {
	cases := conversationRegressionAutoGenCases()
	if len(cases) == 0 {
		t.Skip("no auto-generated regression cases")
	}
	sim := mustTriageAutoGenSimulator(t)
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			local := mustTriageAutoGenSimulator(t)
			local.History = append([]dbMessage{}, sim.History...)
			local.Order = sim.Order
			for _, prior := range tc.priorInputs {
				local.Turn(prior)
			}
			out := local.Turn(tc.input)
			if tc.extraCheck != nil {
				tc.extraCheck(t, out)
				return
			}
			if tc.wantPath != "" && out.Path != tc.wantPath {
				t.Fatalf("path = %q want %q reply=%q", out.Path, tc.wantPath, out.Reply)
			}
		})
	}
}
`)
	return b.String()
}

func fatal(msg string) {
	fmt.Fprintf(os.Stderr, "triage-apply: %s\n", msg)
	os.Exit(1)
}
