package triageautogen

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
	"unicode"
)

// BehaviorRelPath uses the full job UUID (no 8-char collision).
func BehaviorRelPath(jobID string) string {
	return fmt.Sprintf("internal/buyerflow/regression_behavior_%s_test.go", sanitizeJobFileID(jobID))
}

func sanitizeJobFileID(jobID string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(jobID)) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '-' {
			b.WriteRune(r)
		}
	}
	s := b.String()
	if s == "" {
		return "unknown"
	}
	return s
}

func goString(s string) string {
	return strconv.Quote(s)
}

func goStrings(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(goString(s))
	}
	b.WriteString("}")
	return b.String()
}

// HashGeneratedFile detects Composer tampering of immutable tests.
func HashGeneratedFile(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// CartInclude is one required cart line in a generated behavior test.
type CartInclude struct {
	Name string
	Qty  int
}

// BuildBehaviorTestFile generates an immutable buyerflow assertion test.
func BuildBehaviorTestFile(jobID, userText, wantPath string, includes []CartInclude, exclude []string, wantSubstr, wantNot []string) string {
	id := sanitizeJobFileID(jobID)
	var b strings.Builder
	b.WriteString("// Code generated by AI triage behavior loop. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// jobId: %s\n\n", strings.TrimSpace(jobID)))
	b.WriteString("package buyerflow_test\n\n")
	b.WriteString("import (\n\t\"testing\"\n\n\t\"encore.app/wabantu/internal/buyerflow\"\n\t\"encore.app/wabantu/internal/triageassert\"\n)\n\n")
	b.WriteString(fmt.Sprintf("func TestBehavior_%s(t *testing.T) {\n", strings.ReplaceAll(id, "-", "_")))
	b.WriteString("\tsim := buyerflow.NewOmahSimulator()\n")
	b.WriteString(fmt.Sprintf("\tout := sim.Turn(%s)\n", goString(userText)))
	b.WriteString("\tspec := triageassert.CommerceSpec{\n")
	if wantPath != "" {
		b.WriteString(fmt.Sprintf("\t\tWantPath: %s,\n", goString(wantPath)))
	}
	if len(includes) > 0 {
		b.WriteString("\t\tInclude: []triageassert.CartItem{")
		for i, inc := range includes {
			if i > 0 {
				b.WriteString(", ")
			}
			qty := inc.Qty
			if qty < 1 {
				qty = 1
			}
			b.WriteString(fmt.Sprintf("{NameContains: %s, Qty: %d}", goString(inc.Name), qty))
		}
		b.WriteString("},\n")
	}
	if len(exclude) > 0 {
		b.WriteString(fmt.Sprintf("\t\tExcludeNames: %s,\n", goStrings(exclude)))
	}
	if len(wantSubstr) > 0 {
		b.WriteString(fmt.Sprintf("\t\tWantSubstr: %s,\n", goStrings(wantSubstr)))
	}
	if len(wantNot) > 0 {
		b.WriteString(fmt.Sprintf("\t\tWantNot: %s,\n", goStrings(wantNot)))
	}
	b.WriteString("\t}\n")
	b.WriteString("\tif err := triageassert.CheckTurn(out, spec); err != nil {\n")
	b.WriteString("\t\tt.Fatal(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}
