// Package triageautogen writes per-job regression files without colliding symbols.
package triageautogen

import (
	"fmt"
	"strings"
)

func isHexRune(r rune) bool {
	return (r >= '0' && r <= '9') || (r >= 'a' && r <= 'f') || (r >= 'A' && r <= 'F')
}

// AutoGenJobSuffix is the first 8 hex characters of a job UUID (no dashes).
func AutoGenJobSuffix(jobID string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(strings.TrimSpace(jobID)) {
		if isHexRune(r) {
			b.WriteRune(r)
		}
	}
	s := b.String()
	if len(s) > 8 {
		s = s[:8]
	}
	if s == "" {
		s = "unknown"
	}
	return s
}

// AutoGenRelPath is the repo-relative path for one job's auto-gen test file.
func AutoGenRelPath(jobID string) string {
	return fmt.Sprintf("internal/buyerflow/regression_autogen_%s_test.go", AutoGenJobSuffix(jobID))
}

// RewriteAutoGenSymbols suffixes shared identifiers so two jobs can coexist.
func RewriteAutoGenSymbols(src, suffix string) string {
	suffix = strings.TrimSpace(suffix)
	if suffix == "" || src == "" {
		return src
	}
	already := "triageAutoGenSnapshotJSON_" + suffix
	if strings.Contains(src, already) {
		return src
	}
	replacer := strings.NewReplacer(
		"conversationRegressionAutoGenCases", "conversationRegressionAutoGenCases_"+suffix,
		"simulatorFromTriageAutoGenSnapshot", "simulatorFromTriageAutoGenSnapshot_"+suffix,
		"mustTriageAutoGenSimulator", "mustTriageAutoGenSimulator_"+suffix,
		"TestRegressionAutoGen", "TestRegressionAutoGen_"+suffix,
		"triageAutoGenSnapshotJSON", "triageAutoGenSnapshotJSON_"+suffix,
	)
	return replacer.Replace(src)
}

const autoGenHarnessTmpl = `
func mustTriageAutoGenSimulator_%[1]s(t *testing.T) *Simulator {
	t.Helper()
	if triageAutoGenSnapshotJSON_%[1]s == "" {
		return NewOmahSimulator()
	}
	sim, err := SimulatorFromSnapshotJSON(triageAutoGenSnapshotJSON_%[1]s)
	if err != nil {
		t.Fatalf("triage snapshot: %%v", err)
	}
	return sim
}

func TestRegressionAutoGen_%[1]s(t *testing.T) {
	cases := conversationRegressionAutoGenCases_%[1]s()
	if len(cases) == 0 {
		t.Skip("no auto-generated regression cases")
	}
	sim := mustTriageAutoGenSimulator_%[1]s(t)
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			local := mustTriageAutoGenSimulator_%[1]s(t)
			local.History = append([]Message{}, sim.History...)
			local.Order = sim.Order
			for _, prior := range tc.priorInputs {
				local.Turn(prior)
			}
			out := local.Turn(tc.input)
			if tc.extraCheck != nil {
				tc.extraCheck(t, out)
				return
			}
			if tc.wantPath != "" && out.Path != tc.wantPath {
				t.Fatalf("path = %%q want %%q reply=%%q", out.Path, tc.wantPath, out.Reply)
			}
		})
	}
}
`

// BuildAutoGenTestFile wraps GenerateRegressionCases output with a unique test harness.
func BuildAutoGenTestFile(jobID, generated string) string {
	suffix := AutoGenJobSuffix(jobID)
	generated = strings.TrimSpace(generated)
	if strings.HasPrefix(generated, "package buyerflow") {
		generated = strings.TrimSpace(strings.TrimPrefix(generated, "package buyerflow"))
	}
	if !strings.Contains(generated, "triageAutoGenSnapshotJSON") {
		generated = "const triageAutoGenSnapshotJSON = \"\"\n\n" + generated
	}
	generated = RewriteAutoGenSymbols(generated, suffix)

	var b strings.Builder
	b.WriteString("// Code generated by AI triage loop. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// jobId: %s\n\n", strings.TrimSpace(jobID)))
	b.WriteString("package buyerflow\n\n")
	b.WriteString("import \"testing\"\n\n")
	b.WriteString(generated)
	if !strings.HasSuffix(generated, "\n") {
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf(autoGenHarnessTmpl, suffix))
	return b.String()
}
